name: Treat Wheel Zygisk CI

on:
  push:
    branches: [ main ]

  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup NDK_PATH
        run: echo "NDK_PATH=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build with make
        env:
          IS_GITHUB_ACTION: true
        run: make all -j$(nproc)

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          path: build/out/TreatWheel-v*-release.zip
          archive: false

      - name: Upload debug
        uses: actions/upload-artifact@v7
        with:
          path: build/out/TreatWheel-v*-debug.zip
          archive: false
